### ISSUE TITLE
properties node offline

### ISSUE THREAD

**Issue by hditter** [arduino/node-red-contrib-arduino-iot-cloud#38]
I successfully ran a node-red flow reading the upstream values of a sensor in the arduino IoT cloud for many months. Recently, I realised that all arduino nodes were offline. It might coincide with an upgrade of node-red to 3.02 (I am running node-red in Homeassistant). I tried to reproduce the issue by installing node-red on a different raspberry and then adding an arduino  property node. I inserted the client id and secret and get the things and property displayed, but when deploying, node-red crashes with the following error message: ArduinoCloudError: Error: Connection refused: Not authorized
    at MqttClient.<anonymous> (/home/pi/.node-red/node_modules/@arduino/node-red-contrib-arduino-iot-cloud/arduino-iot-client-mqtt/arduino-iot-client-mqtt.js:121:11)
Any help will be appreciated.

**Comment by ilcato** [comment]
@hditter can you test now ?

**Comment by hditter** [comment]
yes, I could!

**Comment by hditter** [comment]
I tested on the node-red instance of Homeassistant, no success. I can’t deploy. Error message is 502 Bad gateway! Gnix 
I then tested on a stand-alone instance on a dedicated Raspberry and there it works now.

**Comment by ilcato** [comment]
So, it's a different error. Can you restart Home Assistant ?

**Comment by hditter** [comment]
Works again, after restarting the HA instance!

**Comment by ilcato** [comment]
ok

**Comment by hditter** [comment]
It seems to work now! Thanks for the help! I will close the issue then.
