### ISSUE TITLE
Unable to install arduino iot node on Node Red

### ISSUE THREAD

**Issue by KennyMarko** [arduino/node-red-contrib-arduino-iot-cloud#54]
![image](https://github.com/arduino/node-red-contrib-arduino-iot-cloud/assets/56265224/647c9e5b-d3d5-46ce-9bd4-6b6c9a6e2590)

[2024-03-13T18_53_07_001Z-debug-0.log](https://github.com/arduino/node-red-contrib-arduino-iot-cloud/files/14592464/2024-03-13T18_53_07_001Z-debug-0.log)

I have tried installing the node from the palettes tab, but I keep getting this error. I have attached the log file and a screenshot of executing the command on cmd.

**Comment by ilcato** [comment]
Do you have git installed on the machine?

**Comment by KennyMarko** [comment]
Yes. I have it installed now. I also checked if its in the environment variables path. 

However I still get an error when I try to install the node,

![image](https://github.com/arduino/node-red-contrib-arduino-iot-cloud/assets/56265224/fc014519-b811-464b-8ffe-1e2e52e3b48b)
[2024-03-15T08_09_10_718Z-debug-0.log](https://github.com/arduino/node-red-contrib-arduino-iot-cloud/files/14612701/2024-03-15T08_09_10_718Z-debug-0.log)

**Comment by ilcato** [comment]
Can you tell us something more about your setup? OS version, node version, node-red version, ...

**Comment by KennyMarko** [comment]
OS version - windows
Npm version - 10.2.4
Node red version -v3.1.6
Node.js version - v20.11.1


Please let me know what other info you need. Thank you

**Comment by ilcato** [comment]
Did you try to install the module manually via command line?

**Comment by KennyMarko** [comment]
yes, i used powershell

**Comment by ilcato** [comment]
The debug log you posted doesn't contain errors. Is it the correct one? can try again to insta via powershell and post the error log file?

**Comment by KennyMarko** [comment]
Thank you! I reinstalled Node-Red and restarted the server. It seemed all I had to do was just restart the server after installing git. Thank you so much!
